config/routes.rb
Rails.application.routes.draw do
  get "/dashboard" => 'dashboard#index', as: :dashboard

  resources :properties
  devise_for :accounts
 root to: 'public#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  mount_uploader :image, ProfilePictureUploader

  has_many :properties

  def full_name
  	"#{first_name} #{last_name}"
  end

  def company
  	"Ipet"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	belongs_to  :account

	scope :latest, -> {order created_at: :desc}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:update, keys: [:first_name, :last_name, :url, :image, :image_cache, :company])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar
  
  def index
  end

  private
  def set_sidebar
      @show_sidebar = true
   end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, expect: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Estabelecimento criando com sucesso.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Estabelecimento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Estabelecimento deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :details, :photo, :photo_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  	@properties = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def profile_picture account, width = 120, height = 120
		thumb = account.image.present? ? account.image.thumb.url : "banner.jpg"
		image_tag thumb, width: width, height: height, class: "profile-pic img-circle"
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

	def property_thumbnail property
		img = property.photo.present? ? property.photo.thumb.url : ""
		image_tag img, class: "property-thumb recipe-show"
	end

	def property_thumbnail_url property
		property.photo.present? ? property.photo.thumb.url : ""
	end
	
	def property_photo_url property
		property.photo.present? ? property.photo.url : asset_url("")
	end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <button type="button" class="btn btn-sm btn-outline-secondary">Compartilhar</button>
      <button type="button" class="btn btn-sm btn-outline-secondary">Exporta</button>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
      This week
    </button>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        <td>cursus</td>
        <td>ante</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>dapibus</td>
        <td>diam</td>
        <td>Sed</td>
        <td>nisi</td>
      </tr>

    </tbody>
  </table>
</div> 

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_agent_details.html.erb
<div class="text-center border pt-4 pb-4 ml-4">
	<div class="mb-2">
		<%= profile_picture @agent %>
	</div>
	<h3 class="h4"><%= @agent.full_name %></h3>
	<p><%= @agent.company %><p>

	<button class="btn btn-info text-uppercase">Telefone </button>
	<button class="btn btn-primary text-uppercase">Email</button>
</div>

app/views/layouts/_footer.html.erb
<footer class="pt-4 pt-sm-5 pt-md-6 pt-lg-7" id="footer">
	<div class="container">
		<div class="row d-flex flex-sm-wrap flex-xs-wrap pb-3 pb-sm-4">

			<div class=" col pb-4 d-sm-block">
				<header class="pb-2">
					<h2>Contato</h2>
				</header>

				<div class="content" id="contact">
                        <p class="font-weight-bold m-0">
                            <span class="select">
                                <a href="" target="_blank">(81) 3346-8888</a><br/>
                                <a href="" target="_blank">(81) 98820-2225</a>
                            </span><span class="mx-1"></span>
                        </p>
                             
                        <p class="font-weight-bold mt-3">
                            <span class="select">Av. Santo Brazica de Luanda, 1996 <br> - Conj. 512  Dr. Silva - Recife, PE</span>
                        </p>
                        
                        <p>
                            <span class="select">
                                <div class="d-block font-weight-bold">
                                    <a href="alexsilva10s@hotmail.com" target="_blank">
                                        <span class="__cf_email__" data-cfemail="8ae9e5e4feebfee5cafaeffee8e5e5e1e3e4eda4e9e5e7a4e8f8">alexsilva10s@hotmail.com</span>
                                    </a>
                                </div>
                            </span>
                        </p>
                </div>
			</div>

			<div class="col pb-4 d-sm-block">
                    
                    <header class="pb-2">
                        <h2>Mais Informações</h2>
                    </header>
                    
                    <div class="content" id="info">
                        <ul class="list-unstyled font-weight-bold">
                            <li><p><a href="/quem-somos">Quem Somos</a></p></li>
                            <li><p><a href="#">Empresas</a></p></li>
                            <li><p><a href="/privacidade">Política de Privacidade</a></p></li>
                            <li><p><a href="/termos-de-uso">Termos de Uso</a></p></li>
                            <li><p><a href="#">Dúvidas Frequentes FAQ</a></p></li>
                            <li><p><a href="/contact-us">Fale Conosco</a></p></li>
                        </ul>
                    </div>
                    
                </div>
                
                <div class="col pb-4 d-sm-block">
                    <header class="pb-2">
                        <h2> Nossos Parceiros</h2>
                    </header>
                    
                    <div class="content" id="partners">
                        <div class="row d-flex flex-wrap">
                            
                            <div class="col mt-3">
                                <a href="http://alexdesign.epizy.com/" target="_blank"><img alt="AlexDesign" src="https://via.placeholder.com/150x40" />
                                </a>
                            </div>
                            
                            <div class="col mt-3">
                                <a href="http://alexdesign.epizy.com/" target="_blank"><img alt="AlexDesign" src="https://via.placeholder.com/250x80" />
                                </a>
                            </div>
                            
                            <div class="col mt-3">
                                <a href="http://alexdesign.epizy.com/" target="_blank"><img alt="AlexDesign" style="width: 10em" src="https://via.placeholder.com/200x80" />
                                </a>
                            </div>
                            
                            <div class="col mt-3">
                                <a href="http://alexdesign.epizy.com/" target="_blank"><img alt="AlexDesign" style="width: 10em" src="https://via.placeholder.com/150x40" />
                                </a>
                            </div>
                            
                        </div>
                    </div>
                </div>
		</div>

		<div class="row footer-copy">
            <div class="col-12">
                <span class="d-flex align-items-center pt-4 pb-4 pt-md-3 pb-md-3">
                    <p class="m-0 footer-cred">Serviços e Desenvolvimento de Web e Software AlexDesign - Ipet Todos os Direitos Reservados</p>
                    <a target="_blank" class="d-none d-md-flex ml-auto" href="http://alexdesign.epizy.com/"><img alt="Desenvolvido por Alex Silva" src="https://via.placeholder.com/86x26" width="86" height="26" />
                    </a>
               	</span>
            </div>
        </div>
	</div>
</footer>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>Ipet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&display=swap" rel="stylesheet">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta content="Agendamento online em Pet Shops, Clínicas Veterinárias, Hotéis, Adestradores, Passeadores e mais" name="description" />
    <meta content="Ipet, banho, tosa, clínica veterinária, consulta, hotelzinho, petshops, passeadores, leva e traz, sistema de agendamento online." name="keywords" /><!--[if lt IE 9]><![endif]--> 

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://unpkg.com/feather-icons"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show-sidebar" if @show_sidebar.present? %>">
    <% if @show_sidebar.nil? %>
      <header>
        <%= render "layouts/nav/public" %>
      </header>

      <%= yield %>
    <% else %>
      <%= render "layouts/nav/dashboard" %>

      <div class="container-fluid">
          <div class="row">
            <%= render "layouts/nav/sidebar" %>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
              <%= yield %>
            </main>
          </div>
      </div>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/footer" %>

    <p id="notifications"><%= notice %></p>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Ipet</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Sair", destroy_account_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark header-blue fixed-top">
  <div class="container">
    <%= link_to image_tag("logo-white.png", alt: "logo ipet"), root_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault"> <ul
    class="navbar-nav nav-header mr-auto"> <li class="nav-item  active"> <a
    class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li> <li class="nav-item"> <a class="nav-link" href="#">Para empresas</a>
    </li>

        <% if account_signed_in? %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Bem vindo</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <%= link_to "Editar conta", edit_account_registration_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Sair", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Entrar", new_account_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cadastra-se", new_account_registration_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Faça sua buscar" aria-label="Search">
        <%= link_to image_tag("ico-search_white.png", type: "submit", class: "ico-search"), root_path %>
      </form> -->
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path, class: "nav-link" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
          Dashboard <span class="sr-only">(current)</span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to properties_path, class: "nav-link" do %>
          <i data-feather="shopping-bag"></i>
          Estabelecimento
        <% end %>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
          Products
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
          Customers
        </a>
      </li>

      <li class="nav-item">
        <%= link_to edit_account_registration_path, class: "nav-link" do %>
          <i data-feather="settings"></i>
          Configurações da conta
        <% end %>
      </li>
      

      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
          Reports
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
          Integrations
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Current month
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Last quarter
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Social engagement
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Year-end sale
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/properties/_agent_details_html.erb
<div class="">
	<h3 class="h4"><%= @agent.full_name %></h3>
	<p><%= @agent.company %><p>

	<button class="btn btn-info text-uppercase">Telefone </button>
	<button class="btn btn-primary text-uppercase">Email mas detalhes</button>
</div>

app/views/properties/_list.html.erb
<% properties.each do |property| %>

	<div class="col-4 mb-5">
		<div class="property bg-white borde">
			<%= link_to property_path(property) do %>

				<div class="property-thumb" style="background-image: url(<%= property_thumbnail_url(property) %>)">
					<%= link_to "", property_path(property) %>
				</div>

				<div class="property-summary p-3">
					<h3 class="h5"><%= link_to property.name, property_path(property) %></h3>
					<p class="mt-2 business-location "><i class ="mr-2" width="12" data-feather="map-pin"></i><%= property.address %></p>
				</div>

			<% end %>
		</div>
	</div>

<% end %>

app/views/properties/edit.html.erb
<h2 class="mb-3 mt-3">Editar Estabelecimento</h2>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="mb-3">Estabelecimento</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Ver', property %></td>
        <td><%= link_to 'Editar', edit_property_path(property) %></td>
        <td><%= link_to 'Deletar', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Estabelecimento', new_property_path, class: "btn btn-primary" %>

app/views/properties/new.html.erb
<h2>Novo Estabelecimento</h2>

<%= render 'form', property: @property %>

<%= link_to 'Cancelar', properties_path %>